### ISSUE TITLE
Queda en blanco al loguearse

### ISSUE THREAD

**Issue by mcjarod** [diniremix/ControlParking#1]
Buenas tengo 
Apache/2.4.9 (Win32) 
PHP/5.5.11
mysqlnd 5.0.11
pero al loguearme con admin admin o demo demo se queda en una página en blanco con http://localhost/controlparking/validate.php espero me pueda ayudar

**Comment by diniremix** [comment]
- Hacer un pull con los ultimos cambios de la aplicación.
- Revisar commit bde02c7
- Revisar las credenciales para que el acceso a la base de datos este correcto.

**connections/conexion.php**
```php
$hostname_conexion = "localhost";
$database_conexion = "parkingdb";
$username_conexion = "root";
$password_conexion = "";
```
- Seguir el proceso de [instalación.](https://github.com/diniremix/ControlParking#instalaci%C3%B3n)

**Comment by mcjarod** [comment]
Gracias el problema era la contraseña a la base de datos!

**Comment by diniremix** [comment]
cerrando este issue.
